Don't die just because the system wasn't found in server's database

diff --git a/client/forest-client b/client/forest-client
--- a/client/forest-client
+++ b/client/forest-client
@@ -182,9 +182,13 @@ updates=`get_available_updates`
 if [ "x$updates" != "x" ]; then
 	error_check=`echo $updates | cut -d ":" -f 1`
 	if [ "x$error_check" = "xerror" ]; then
-		echo "Error getting available updates"
-		echo "$updates"
-		exit 1
+		error_check=`echo $updates | cut -d ":" -f 3`
+		error_check=`trim_spaces $error_check`
+		if [ "x$error_check" != "xSystem not found in database" ]; then
+			echo "Error getting available updates"
+			echo "$updates"
+			exit 1
+		fi
 	else
 		updates=`spaces_to_commas "$updates"`
 		updates=`encode_for_html "$updates"`
