Seperated return value checks

diff --git a/client/forest-collect-cron b/client/forest-collect-cron
--- a/client/forest-collect-cron
+++ b/client/forest-collect-cron
@@ -3,11 +3,18 @@
 # only run if the package is completely installed
 test -x /usr/sbin/forest-collect || exit 0
 
-returndata=`/usr/sbin/forest-collect | grep -v "data ok"`
-# Grep returns 1 if it finds the search string, but that makes cron complain.
-# A return value of 2 or greater means there really was an error, so we want to
-# see the error message in that case.
-if [ $? -gt 1 ]
+returndata=`/usr/sbin/forest-collect`
+if [ $? -ne 0 ]
 then
+	echo "forest-collect return value: $?\n"
+	echo $returndata
+fi
+
+returndata=`echo $returndata | grep -v "data ok"`
+# Grep returns 0 if it finds the search string, or 1 if it doesn't.
+# A return value of anything but 0 means we want to see the message.
+if [ $? -ne 0 ]
+then
+	echo "grep return value: $?\n"
 	echo $returndata
 fi
